baseURL = "https://examplesn.com"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin Community Site"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin Community Site"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


# Main Menu
[[menu.main]]
    name = "News"
    title = "News"
    weight = -120
    identifier = "news"
    url = "/news/"
[[menu.main]]
    name = "Community projects"
    title = "Projects"
    weight = -110
    identifier = "Project"
    url = "/projects/"
[[menu.main]]
    name = "Roadmap"
    title = "Roadmap"
    weight = -110
    identifier = "Roadmap"
    url = "/roadmap/"
[[menu.main]]
    name = "Get involved"
    title = "Get Involved"
    weight = -100
    url = "/get-involved/"
    identifier = "get-involved"
[[menu.main]]
    name = "Who runs this?"
    title = "Who Runs This?"
    weight = -100
    url = "/who-runs-this/"
    identifier = "who-runs-this"